variables:
  COMPOSE_PROJECT_NAME: $CI_PROJECT_NAME-$CI_BUILD_REF_NAME
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  GIT_SUBMODULE_STRATEGY: recursive
  IMAGE_TAG_BUILD: $CI_COMMIT_SHA
  IMAGE_TAG_RELEASE: $CI_COMMIT_REF_NAME

stages:
  - build
  - test
  - release
  - deploy

before_script:
  - curl -L https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip -o protoc.zip
  - apt update && apt install -y unzip
  - unzip protoc.zip
  - export PATH=$PATH:$(pwd)/bin/
  - echo $PATH
  - echo $(ls)
  - pip install tox
  - make protobuf

test:py27:
  stage: test
  image: python:2.7
  script:
    - tox
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

test:py34:
  stage: test
  image: python:3.4
  script:
    - tox

test:py35:
  stage: test
  image: python:3.5
  script:
    - tox

test:py36:
  stage: test
  image: python:3.6
  script:
    - tox

test:py37:
  stage: test
  image: python:3.7
  script:
    - tox
